---
- name: Install base system packages
  ansible.builtin.import_tasks: base.yml

- name: Install the Python toolchain
  ansible.builtin.import_tasks: python.yml

- name: Install the Node toolchain
  ansible.builtin.import_tasks: node.yml
