---
- name: Configure SSH hardening
  ansible.builtin.import_tasks: sshd.yml

- name: Configure the firewall
  ansible.builtin.import_tasks: firewall.yml

- name: Configure fail2ban
  ansible.builtin.import_tasks: fail2ban.yml

- name: Configure automatic security updates
  ansible.builtin.import_tasks: updates.yml
